In [1]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(a)


[ 1  2  3  4  5  6  7  8  9 10]


In [14]:
matrix = np.zeros((3, 3))

In [3]:
array = np.random.randint(1, 11, size=(5, 5), dtype=int)

print(array)

[[ 9  6  5  4  5]
 [ 1  2  6  9  1]
 [ 6  6  1  1 10]
 [ 6 10  1  7  4]
 [ 9  9  2  4  7]]


In [4]:
array_float = np.random.rand(4, 4)

print(array_float)

[[0.28002359 0.15520698 0.88377809 0.38841375]
 [0.13628775 0.10653081 0.16309062 0.41381554]
 [0.81167894 0.64821314 0.84255466 0.5786306 ]
 [0.94914817 0.21920561 0.22576691 0.30554603]]


In [5]:
a = np.random.randint(1, 11, size=(5, 5), dtype=int)
b = np.random.randint(1, 11, size=(5, 5), dtype=int)

print (a + b)
print (a - b)
print (a * b)


[[14 19 10 13  9]
 [13 13 10 11 11]
 [19 14 11 15 16]
 [15 10 15  4 10]
 [11  6  6 13 11]]
[[-4 -1 -2  5  1]
 [-3  7  8  5 -3]
 [ 1  0  1 -3  2]
 [-5 -6 -1  0 -8]
 [ 7 -4 -2  7  1]]
[[45 90 24 36 20]
 [40 30  9 24 28]
 [90 49 30 54 63]
 [50 16 56  4  9]
 [18  5  8 30 30]]


In [6]:
a = np.array([1, 2, 3, 4, 5, 6, 7])
b = np.array([1, 2, 3, 4, 5, 6, 7])
print(np.dot(a, b))

140


In [7]:
matrix1 = np.random.randint(1, 11, size=(2, 2))
matrix2 = np.random.randint(1, 11, size=(2, 3))

print(np.dot(matrix1, matrix2))


[[ 31  32  43]
 [105  85 126]]


In [8]:
matrix_1 = np.random.randint(1, 11, size=(3, 3))

a_inv = np.linalg.inv(matrix_1)
print(a_inv)

[[-0.16176471  0.29411765 -0.01470588]
 [ 0.33823529 -0.20588235 -0.01470588]
 [-0.04411765 -0.14705882  0.13235294]]


In [9]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 1, 2]])

print(a)
b = a.T
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10  1  2]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7  1]
 [ 4  8  2]]


In [10]:
matrix = np.random.randint(1, 11, size=(3, 4), dtype=int)
vector = np.random.randint(1, 11, size=4, dtype=int)

print(np.dot(matrix, vector))

[140 169 105]


In [11]:
matrix = np.random.rand(2, 3)
vector = np.random.rand(3)

print(np.dot(matrix, vector))

[0.22003389 0.90501895]


In [12]:
matrix_1 = np.random.randint(1, 11, size=(2, 2), dtype=int)
matrix_2 = np.random.randint(1, 11, size=(2, 2), dtype=int)

print(np.multiply(matrix_1, matrix_2))

[[72 16]
 [24 28]]


In [13]:
matrix1 = np.random.randint(1, 11, size=(2, 2), dtype=int)
matrix2 = np.random.randint(1, 11, size=(2, 2), dtype=int)

print(np.dot(matrix1, matrix2))

[[47 89]
 [50 78]]


In [15]:
matrix = np.random.randint(1, 101, size=(5, 5), dtype=int)
print(matrix.sum())

1392


In [16]:
matrix1 = np.random.randint(1, 11, size=(4, 4), dtype=int)
matrix2 = np.random.randint(1, 11, size=(4, 4), dtype=int)

print(np.subtract(matrix1, matrix2))

[[ 2 -9 -2  3]
 [ 1  4  2 -3]
 [ 3 -4 -3 -2]
 [ 1  4  0 -5]]


In [17]:
matrix = np.random.rand(3, 3)
print(matrix)
row_sums = np.sum(matrix, axis=1, keepdims=True)
print(row_sums)

[[0.8427489  0.55259351 0.79231341]
 [0.4513523  0.26737364 0.44878626]
 [0.6421912  0.25129558 0.09044833]]
[[2.18765581]
 [1.16751221]
 [0.98393511]]


In [18]:
matrix = np.random.randint(1, 11, size=(3, 4))
print(matrix)
squared_matrix = np.square(matrix)
print(squared_matrix)

[[ 3 10  7  8]
 [ 1  8  2  7]
 [ 3  3  4  7]]
[[  9 100  49  64]
 [  1  64   4  49]
 [  9   9  16  49]]


In [19]:
vector = np.random.randint(1, 51, size=4)
print(vector)

sqrt_vector = np.sqrt(vector)
print(sqrt_vector)

[46 21  1 15]
[6.78232998 4.58257569 1.         3.87298335]
